services:

  db:
    image: postgres:16
    container_name: cinema_db
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cinema_pgdata:/var/lib/postgresql/data
    networks:
      - cinema_net

  keycloak-db:
    image: postgres:16
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data
    networks:
      - cinema_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: cinema_keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_URL: http://cinema_keycloak:8080
      KC_HOSTNAME_STRICT: false

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    networks:
      - cinema_net

  backend:
    build: .
    container_name: cinema_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cinema
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - cinema_net

volumes:
  cinema_pgdata:
  keycloak_pgdata:

networks:
  cinema_net:
